"""auto-vote

Revision ID: 8f2359f612ff
Revises: 514cc0526321
Create Date: 2022-07-22 14:28:08.510425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f2359f612ff'
down_revision = '514cc0526321'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['myposts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('myposts', 'content')
    op.create_table('trades',
    sa.Column('region', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('imports', sa.NUMERIC(precision=50, scale=0), autoincrement=False, nullable=True),
    sa.Column('exports', sa.NUMERIC(precision=50, scale=0), autoincrement=False, nullable=True)
    )
    op.create_table('test_tb',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_tb_pkey')
    )
    op.create_table('notes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='notes_pkey')
    )
    op.drop_table('votes')
    # ### end Alembic commands ###
